### ISSUE TITLE
Decide on the library for working with DB. 

### ISSUE THREAD

**Issue by Krisilda** [bwsw/cs-pulse-server#10]

**Comment by ddpaimon** [comment]
Chose paulgoldbaum/scala-influxdb-client (https://github.com/paulgoldbaum/scala-influxdb-client) as library for InfluxDB.
This async library with MIT license. Last update 3 days ago.
Another choice: influxdata/influxdb-scala with last update 24 Jul 2015.

**Comment by bwsw** [comment]
Why not native https://github.com/influxdata/influxdb-java?

**Comment by ddpaimon** [comment]
There are no objections, they are similar. Chose native.
