### ISSUE TITLE
Implement work with DB.

### ISSUE THREAD

**Issue by Krisilda** [bwsw/cs-pulse-server#11]

**Comment by ddpaimon** [comment]
Estimate time: 2h with tests

**Comment by ddpaimon** [comment]
Add Mockito for mocking. Still remaining time: 30m

**Comment by ddpaimon** [comment]
Don't understood how to use Mockito. Instead of this create MockInfluxDB implementation with only used methods. Still remaining time: 1h

**Comment by ddpaimon** [comment]
Understanding how to use Mockito. Remaining time: 1h

**Comment by ddpaimon** [comment]
Elapsed time: 3.5h

**Comment by bwsw** [comment]
No artifacts, no deliverables, no purpose, no commits.

**Comment by ddpaimon** [comment]
https://github.com/bwsw/cs-pulse-server/commit/f64a7681e81da216f36ee1252a21a932c8d07772
