### ISSUE TITLE
Implement other ViewFabric's and View's

### ISSUE THREAD

**Issue by Krisilda** [bwsw/cs-pulse-server#14]
Factories should fill representations and give completed products to the controller.

**Comment by bwsw** [comment]
Too abstract and meaningless. Decompose.

**Comment by ddpaimon** [comment]
![pulseschema](https://cloud.githubusercontent.com/assets/19563691/26399381/eca11afa-40a6-11e7-983b-b7ba7968aec3.png)

**Comment by ddpaimon** [comment]
Estimated time: 2h

**Comment by ddpaimon** [comment]
Implemented Ram, Disk, Network ViewFabric's and View's
Please check output fields type. If this not so important, I can change it to AnyRef instead of String.

**Comment by ddpaimon** [comment]
Need to change docs.

**Comment by ddpaimon** [comment]
Docs changed - time field removed from response

**Comment by ddpaimon** [comment]
Elapsed time: 4h
