### ISSUE TITLE
Setup an nginx.

### ISSUE THREAD

**Issue by Krisilda** [bwsw/cs-pulse-server#15]
From requirements of the project:
1) implement per-client query limit/sec parameter configurable with ENVARS with Nginx (20 queries per second) 
2) implement behind nginx
3) Configurable nginx cache time (in seconds) for repeatable requests, default 10 seconds

**Comment by bwsw** [comment]
c

**Comment by ddpaimon** [comment]
Estimate time: 7h

**Comment by ddpaimon** [comment]
It takes more time: 2h
I completed create rate limit within nginx. I checked it worked with  curl command.
I sent the request once a 0.01 second, but nginx answered only once a second with 1r/s rate limit config.

**Comment by ddpaimon** [comment]
Did it. I sent 100 request, but origin server answered only twice with "proxy_cache_min_uses    2;" config.
There are several config settings:
- cache path
- max cache size
- inactive (seconds)
- min uses
@bwsw let's set up default values for this settings.

**Comment by ddpaimon** [comment]
- cache path: /var/www/cache
- max cache size: 10g
- inactive: 10s
- min uses: 10

**Comment by ddpaimon** [comment]
Elapsed time: 9h
nginx.conf: https://github.com/bwsw/cs-pulse-server/blob/pulse%2315/nginx.conf
Configurable settings makes through supervisor. It will be added into task #16 (docker)
