### ISSUE TITLE
Build docker container with the project.

### ISSUE THREAD

**Issue by Krisilda** [bwsw/cs-pulse-server#16]
From requirements of the project:
1) build and deploy as docker container,
2) publish to dockerhub

**Comment by bwsw** [comment]
LGTM

**Comment by ddpaimon** [comment]
Estimate time: 7h
Launching server and nginx through supervisor. Implement configurable settings.

**Comment by ddpaimon** [comment]
Hard to understanding how jetty works. Need more time: 2h

**Comment by ddpaimon** [comment]
Understood how the jetty works. Need only jetty-runner and .war file.
Just now I have troubles with .war file creation. I can create this file, but it's not working.
Gives an error message: "No lifecycle class found!"

**Comment by ddpaimon** [comment]
My idea of how this should work:
- take jetty docker image as main|
- install nginx
- prepare war file
- launch supervisor
And supervisor must do:
- ask jetty to launch with .war file
- launch nginx

**Comment by ddpaimon** [comment]
Did a working .war file

**Comment by ddpaimon** [comment]
I can not get to work together nginx and jetty.

**Comment by ddpaimon** [comment]
I completed write dockerfile.
@bwsw it remains to attach to docker hub.

**Comment by ddpaimon** [comment]
Dockerfile: https://github.com/bwsw/cs-pulse-server/blob/pulse%2316/dockerfile
Just now without testing.

**Comment by bwsw** [comment]
1. Optimize all RUN into one command and the same for ADD, to decrease the amount of layers.
2. EXPOSE for port
3. add maintainer information like here: MAINTAINER Bitworks Software info@bitworks.software
4. Update README.md with instruction how to run it from docker hub.

**Comment by ddpaimon** [comment]
Build image via maven (Sonatype)

**Comment by ddpaimon** [comment]
Dockerfile: https://github.com/bwsw/cs-pulse-server/blob/pulse%2316/Dockerfile
Readme: https://github.com/bwsw/cs-pulse-server/blob/pulse%2316/README.md#usage
Elapsed time: 4h
