### ISSUE TITLE
Define the specification of JSON-config

### ISSUE THREAD

**Issue by Krisilda** [bwsw/cs-pulse-server#17]
Need to define the acceptable values of aggregation for a range.
For each resource, it will be the same couples of values.
From the project requirements:
1) < range> - Data output period - 15m, 30m, 1h, 2h, 4h, 12h, 1d, 1w, 1month 
2) <aggregation> - 1m, 5m, 15m, 1h (aggregation must be less then range), example: range=15m, aggregation=5m, in result we have 3 values for needed data.

**Comment by bwsw** [comment]
@Krisilda,
No, they are the same for all type of resources. Just single tree of compatible ranges.

Try to use ticket body to specify extended information.

Also, maximum shift must be provided.

```json
{
  "15m": { 
           "aggregation": ["5m", "1m"],
           "maximum-shift": 2880 // one month in 15m intervals
  },
  "1h": { 
           "aggregation": ["15m", "1m"],
           "maximum-shift": 720
  }
  ...
}
```

**Comment by bwsw** [comment]
I still don't understand what we are going to do here:

1. Implement something to load specification from JSON? file?
2. Validator?
3. Tests?

Work is not clearly defined and can not be estimated properly.

**Comment by ddpaimon** [comment]
1. Specification for what? To running rest needs environment variables (influx connection data).
2. Validator implements via Scalatra Commands. I realize tests for invalid arguments in TestResourceController. But at now there is no implementations(code) for this tests.
3. What's wrong with tests? All components are covered by tests.

**Comment by ddpaimon** [comment]
By now there is no month duration in influxDB. So we can use '30d' for 1 month range.
This comment applies to: range - Data output period - 15m, 30m, 1h, 2h, 4h, 12h, 1d, 1w, 1 month

**Comment by bwsw** [comment]
ok

**Comment by ddpaimon** [comment]
I realized what was going on here. I think this specification included to Controller validation, because it's part of controller. I'll read Scalatra Commands documentation today, and tell my opinion.

**Comment by bwsw** [comment]
I don't think config load is somehow connected to Scalatra, it's general code part.

**Comment by ddpaimon** [comment]
This library can help us with this problem: https://github.com/typesafehub/config
What are you thinking about external lib?

**Comment by bwsw** [comment]
Looks awesome.

**Comment by ddpaimon** [comment]
Need to determine the entire configuration file.

**Comment by bwsw** [comment]
OK

**Comment by ddpaimon** [comment]
Need to describe config file entire before task approved.

**Comment by ddpaimon** [comment]
{  
   "main":{  
      "connection":{  
         "host":"value",
         "port":"value"
      },
      "time":{  
         "range_specs":{  
            "range":"15m",
            "spec":{  
               "aggregation":[  
                  "1m",
                  "5m"
               ]
            }
         }
      },
      "shift_specs":{  
         "spec":[  
            "m",
            "h",
            "d"
         ]
      }
   }
}

**Comment by bwsw** [comment]
Try to use markdown. 
Use separate document in markdown like config.md.

```json
{
   'it': 'is',
   'a': ['jso', {'n',1}]
}
```

**Comment by bwsw** [comment]
@ddpaimon @Krisilda 
Describe every parameter. Don't use abstract names like 'connection'. What is 'connection'. Connection to what? Create table with 'json/path/to/parameter', default value, value domain where you describe every config parameter.

**Comment by ddpaimon** [comment]
https://github.com/bwsw/cs-pulse-server/blob/master/config.md
This is specific JSON format using in typesafe config.

**Comment by ddpaimon** [comment]
We defined the basis of the configuration file. 
Next step  implement configuration loading and using in app.

**Comment by ddpaimon** [comment]
Elapsed time: 1h
