### ISSUE TITLE
Implement additional method to get permitted intervals.

### ISSUE THREAD

**Issue by ddpaimon** [bwsw/cs-pulse-server#20]
Permitted -intervals- are taken from the configuration file.

**Comment by bwsw** [comment]
The task is too abstract. Specify exactly what to do.

**Comment by ddpaimon** [comment]
Method name: permitted_intervals
Return intervals from config as is.

Estimate time: 2h

**Comment by ddpaimon** [comment]
Completed implementation  additional method: https://github.com/bwsw/cs-pulse-server/commit/9f6b04559794f9f158addf5d0b917b71b9aeeec5
Elapsed time: 30m
