### ISSUE TITLE
Implement input parameters validation via Validators.

### ISSUE THREAD

**Issue by ddpaimon** [bwsw/cs-pulse-server#22]
Scalatra Commands is a methods like: uuidValidation, timeValidation. Then this methods used wherever they are needed.
List o full methods:
uuidValidation,
timeValidation.
rangeValidation,
aggregationValidation,
shiftValidation

**Comment by bwsw** [comment]
@ddpaimon @Krisilda 
Don't use "ADD" use "Implement", "design", "draw", "discuss" and other properly defined words. I don't understand what is "ADD".

**Comment by ddpaimon** [comment]
Estimated time: 5h

**Comment by ddpaimon** [comment]
For more information of implementation see #25

**Comment by ddpaimon** [comment]
Additional: return error massages and validation result

**Comment by ddpaimon** [comment]
After validation you must return two values: list of errors and validation result.
Example: (List("Not uuid", "Range not allowed permitted interval"), False)
(List(), True)

**Comment by ddpaimon** [comment]
Completed implementation of Validators: https://github.com/bwsw/cs-pulse-server/commit/002e904da14cbf1b9b926eb1c3bbe1a022e0fc1b

**Comment by ddpaimon** [comment]
Elapsed time: 8h
