### ISSUE TITLE
Implement valid error response

### ISSUE THREAD

**Issue by ddpaimon** [bwsw/cs-pulse-server#29]
1. This is must be valid json
2. Return full response with query parameters

**Comment by ddpaimon** [comment]
Estimate time: 2h

**Comment by bwsw** [comment]
@ddpaimon 
No error response format described in README.md. Describe response format json prior to approve.

**Comment by ddpaimon** [comment]
Error response example: https://github.com/bwsw/cs-pulse-server/blob/develop/README.md#error-response

**Comment by ddpaimon** [comment]
I change error JSON, because app don't known what query is: https://github.com/bwsw/cs-pulse-server/blob/pulse%2329/README.md#error-response
Implemented error view. App returns this view when catch an error.
Elapsed time: 3h
