### ISSUE TITLE
Update REST API documentation

### ISSUE THREAD

**Issue by Krisilda** [bwsw/cs-pulse-server#4]
Description: 
add examples of requests and responses for each of 4 GET request.
describe all fields of JSON with their types (include all parameters which sensor can have).

**Comment by ddpaimon** [comment]
Check current view of Request/Response examples.

**Comment by bwsw** [comment]
Disk request / disk response are copypasted from network and incorrect.

**Comment by bwsw** [comment]
Disk request URL is still buggy.

**Comment by bwsw** [comment]
@Krisilda , what is correct destination if review of the ticked is passed successfully?
