### ISSUE TITLE
Explore Scalatra

### ISSUE THREAD

**Issue by Krisilda** [bwsw/cs-pulse-server#5]
Explore Scalatra features. 
Identify features which are needed for the project. 
Describe the result of research.
Update class diagram if needed.

**Comment by ddpaimon** [comment]
Elapsed time: 7h

Result:
Launch scalatra on jetty server.
Use scalatra JSON viewer for presents scala case classes as JSON.
Understanding scalatra structure.

Next step:
Updating class diagram.
