### ISSUE TITLE
Implement Router

### ISSUE THREAD

**Issue by Krisilda** [bwsw/cs-pulse-server#7]
Implements 4 GET methods of Resorce Controller for each specific resource: cpu, disk, ram, network

**Comment by ddpaimon** [comment]
Estimated time: 1h

**Comment by ddpaimon** [comment]
Implement ResourceController with Scalatra.
Create project skeleton.
By now project is launched via jetty.

**Comment by ddpaimon** [comment]
Elapsed time: 2h
